package com.innbucks.marketplaceservice.config;

import io.micrometer.tracing.Tracer;
import io.micrometer.tracing.otel.bridge.OtelTracer;
import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter;
import io.opentelemetry.sdk.trace.export.SpanExporter;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.env.YamlPropertySourceLoader;
import org.springframework.boot.micrometer.observation.autoconfigure.ObservationAutoConfiguration;
import org.springframework.boot.micrometer.tracing.autoconfigure.MicrometerTracingAutoConfiguration;
import org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.OpenTelemetryTracingAutoConfiguration;
import org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.otlp.OtlpTracingAutoConfiguration;
import org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.otlp.OtlpTracingConnectionDetails;
import org.springframework.boot.opentelemetry.autoconfigure.OpenTelemetrySdkAutoConfiguration;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.core.env.PropertySource;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Export is OFF until a collector is named, and the endpoint is the only switch.
 *
 * <p>Runs the real tracing auto-configuration over this service's own
 * {@code application.yaml} with export ENABLED — {@code @SpringBootTest} turns
 * export off for every test, which would hide exactly what this pins. With no
 * endpoint there is no exporter bean at all, so no batch processor ever opens a
 * connection and nothing logs a failure every five seconds; ids are still
 * generated by the real tracer.
 *
 * <p>Boot itself maps {@code OTEL_EXPORTER_OTLP_TRACES_ENDPOINT} onto
 * {@code management.opentelemetry.tracing.export.otlp.endpoint} and skips an
 * empty variable. The one way to break that is to put the key in
 * {@code application.yaml} as {@code ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:}}:
 * that defines the property as "", which satisfies the exporter's
 * {@code @ConditionalOnProperty} — {@link #applicationYamlDoesNotDefineTheEndpoint()}.
 */
class TracingExportGateTest {

    private static final String ENDPOINT = "management.opentelemetry.tracing.export.otlp.endpoint";

    private final ApplicationContextRunner runner = new ApplicationContextRunner()
            .withInitializer(context -> context.getEnvironment().getPropertySources()
                    .addLast(applicationYaml()))
            .withConfiguration(AutoConfigurations.of(
                    ObservationAutoConfiguration.class,
                    MicrometerTracingAutoConfiguration.class,
                    OpenTelemetrySdkAutoConfiguration.class,
                    OpenTelemetryTracingAutoConfiguration.class,
                    OtlpTracingAutoConfiguration.class))
            .withUserConfiguration(TracingConfig.class);

    @Test
    void noEndpoint_noExporter_butIdsAreStillGenerated() {
        runner.run(context -> {
            assertThat(context).hasNotFailed();
            assertThat(context.getEnvironment().getProperty("management.tracing.export.enabled"))
                    .isEqualTo("true");
            assertThat(context).doesNotHaveBean(OtlpTracingConnectionDetails.class);
            assertThat(context).doesNotHaveBean(SpanExporter.class);
            assertThat(context.getBean(Tracer.class)).isInstanceOf(OtelTracer.class);
        });
    }

    @Test
    void anEndpoint_isTheOnlySwitch_thatCreatesTheExporter() {
        runner.withPropertyValues(ENDPOINT + "=http://otel-collector:4318/v1/traces")
                .run(context -> {
                    assertThat(context).hasNotFailed();
                    assertThat(context).hasSingleBean(OtlpHttpSpanExporter.class);
                });
    }

    @Test
    void samplingDefaultsToTenPercent_propagationIsW3COnly_andLogsAreNeverExported() {
        runner.run(context -> {
            assertThat(context.getEnvironment().getProperty("management.tracing.sampling.probability"))
                    .isEqualTo("0.1");
            assertThat(context.getEnvironment().getProperty("management.tracing.propagation.type"))
                    .isEqualTo("W3C");
            assertThat(context.getEnvironment().getProperty("management.logging.export.otlp.enabled"))
                    .as("logs never leave over OTLP").isEqualTo("false");
        });
    }

    @Test
    void applicationYamlDoesNotDefineTheEndpoint() throws IOException {
        for (PropertySource<?> document : new YamlPropertySourceLoader()
                .load("application.yaml", new ClassPathResource("application.yaml"))) {
            assertThat(document.containsProperty(ENDPOINT))
                    .as("application.yaml (%s) must not define %s; Boot maps "
                            + "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT itself", document.getName(), ENDPOINT)
                    .isFalse();
        }
    }

    /** The default (profile-less) document of the real application.yaml. */
    private static PropertySource<?> applicationYaml() {
        try {
            List<PropertySource<?>> documents = new YamlPropertySourceLoader()
                    .load("application.yaml", new ClassPathResource("application.yaml"));
            return documents.get(0);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
